name: watch_store
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  badges: ^3.1.2
  floating_navbar: ^2.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_onboarding_slider: ^1.0.11
  glassmorphism: ^3.0.0
  icons_plus: ^4.0.0
  onboarding: ^3.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Unna
      fonts:
        - asset: fonts/Unna-Bold.ttf
          weight: 700
        - asset: fonts/Unna-Regular.ttf
          weight: 400
