name: shopping_watch_application_bloc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.1
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  dot_navigation_bar: ^1.0.2
  glass: ^1.0.2+1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/logo.png
  - assets/images/watches/
  - assets/images/users/
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: fonts/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: fonts/PlayfairDisplay-Medium.ttf
          weight: 600
        - asset: fonts/PlayfairDisplay-Regular.ttf
          weight: 500
          