name: wach_store_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  another_carousel_pro: ^1.0.0
  dot_navigation_bar: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_carousel_widget: ^2.1.2
  glass: ^1.0.2+1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - lib/assets/images/
  fonts:
   - family: Crimson 
     fonts:
      - asset: lib/assets/fonts/CrimsonText-Regular.ttf
